### ISSUE TITLE
Song info does not display in iTunes 12.2.2.25

### ISSUE THREAD

**Issue by blamonet** [illusori/bash-itunes#5]
:~/bash-itunes → ./itunes info                                                                                                                                                 
Currently playing "" ()

:~/bash-itunes → ./itunes next                                                                                                                                                 
Skipping to next track, "" ()

Other than that, it still plays and can skip tracks like normal. I think the structure of the data coming in has changed. I noticed it wasn't able to convert data into a string.

Example of what use to work:
tell application "iTunes" to artist of current track as string'
Output:
Can’t make «class pArt» of «class pTrk» of application "iTunes" into type string. (-1700)

**Comment by blamonet** [comment]
Apple Music issue, not normal iTunes Library issue. Closing.

**Comment by loretoparisi** [comment]
@blamonet interesting fact: 

```shell
$ osascript -e 'tell application "iTunes" to player position as string
71,499000549316
```

it works with AppleMusic.
